package com.sarality.app.extract;

import java.util.List;

/**
 * Holds a Message and the Events generated by the Message
 *
 * @param <E> Type of Event being generated from the message
 * @param <M> Type of Message from which the events are generated.
 *
 * @author abhideep@ (Abhideep Singh)
 */
public class MessageEventList<M, E> {
  private final List<E> eventList;
  private final M message;

  /**
   * Constructor.
   *
   * @param message Source message
   * @param eventList List of events generated from message.
   */
  public MessageEventList(M message, List<E> eventList) {
    this.message = message;
    this.eventList = eventList;
  }

  /**
   * @return Source Message.
   */
  public M getMessage() {
    return message;
  }

  /**
   * @return List of generated events.
   */
  public List<E> getEvents() {
    return eventList;
  }
}
